# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9df542208cf3250e64942096be868aee6028dec54c911fcf291f7821c7982935f5258db1197eb17b792806416efc3c6ea9e39380e25d884f8e156e9cbff81305

test:
  secret_key_base: 8177b616bdf496c09e62df91d6f82d293fefea4003f54372a5d7e19677479e78c86e42c36b1c815f465921b50a8a6c16066687d13399024ed4bef9ad82a0a475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
